name: Go

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.19
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Lint
      run: |
        test -n "$(make fmt)" && echo >&2 "Linting failed" && exit 1

    - name: Test
      run: make test
